#version 460
#pragma unroll
#pragma optionNV(unroll all)

#extension GL_EXT_buffer_reference : require
#extension GL_EXT_shader_explicit_arithmetic_types_int8 : require
#extension GL_EXT_shader_explicit_arithmetic_types_int16 : require
#extension GL_EXT_shader_explicit_arithmetic_types_int64 : require
#extension GL_KHR_shader_subgroup_basic : require
#extension  GL_KHR_shader_subgroup_arithmetic : require

#moj_import <nvidium:occlusion/scene.glsl>

layout(local_size_x = 32) in;

uint getReflectedTranslucentSectionId(uint sectionId) {
    ivec4 header = sectionData.data[sectionId].header;
    if (!sectionEmpty(header)) {
        sectionId &= ~0xFFu;
        sectionId |= uint((header.y>>18)&0xFFu);
    }
    return sectionId;
}

bool hasTranslucentData(uint sectionId) {
    return sectionData.data[sectionId].tranlucentQuadCount > 0;
}

void main() {
    uint baseSectionId = uint(regionIndicies.data[gl_WorkGroupID.x]) << 8;

    if (regionVisibility.data[gl_WorkGroupID.x] == uint8_t(0)) {
        // Region was not visible, reset visibility bits
        for (uint i = 0; i < 8; i++) {
            uint index = baseSectionId + gl_LocalInvocationID.x * 8 + i;
            sectionVisibility.data[index] = uint8_t(0);
        }

        if (subgroupElect()) {
            terrainCommandBuffer.data[gl_WorkGroupID.x] = uvec4(0);
            translucencyCommandBuffer.data[(uint(regionCount) - gl_WorkGroupID.x) - 1] = uvec4(0);
            temporalCommandBuffer.data[gl_WorkGroupID.x] = uvec4(0);
        }
        return;
    }

    uvec3 renderCounts = uvec3(0);
    for (uint i = 0; i < 8; i++) {
        uint visibilityIndex = baseSectionId + gl_LocalInvocationID.x * 8 + i;
        uint8_t visibilityData = sectionVisibility.data[visibilityIndex];

        uint translucentVisibilityIndex = getReflectedTranslucentSectionId(visibilityIndex);
        uint8_t translucentVisibilityData = sectionVisibility.data[translucentVisibilityIndex];

        renderCounts += uvec3(
            uint((visibilityData & 1u) == 1),
            uint((translucentVisibilityData & 1u) == 1 && hasTranslucentData(translucentVisibilityIndex)),
            uint((visibilityData & 3u) == 1)
        );
    }

    uvec3 workId = subgroupExclusiveAdd(renderCounts);
    uvec3 totalSectionCount = subgroupAdd(renderCounts);

    for (uint i = 0; i < 8; i++) {
        uint visibilityIndex = baseSectionId + gl_LocalInvocationID.x * 8 + i;
        uint visibilityData = sectionVisibility.data[visibilityIndex];

        if ((visibilityData & 1u) == 1) {
            sectionIndices.data[baseSectionId + workId.x++].x = uint8_t(visibilityIndex & 0xFF);
        }

        uint translucentVisibilityIndex = getReflectedTranslucentSectionId(visibilityIndex);
        uint translucentVisibilityData = sectionVisibility.data[translucentVisibilityIndex];

        if ((translucentVisibilityData & 1u) == 1 && hasTranslucentData(translucentVisibilityIndex)) {
            sectionIndices.data[baseSectionId + workId.y++].y = uint8_t(translucentVisibilityIndex & 0xFF);
        }

        if ((visibilityData & 3u) == 1) {
            sectionIndices.data[baseSectionId + workId.z++].z = uint8_t(visibilityIndex & 0xFF);
        }
    }

    if (subgroupElect()) {
        terrainCommandBuffer.data[gl_WorkGroupID.x] = uvec4(totalSectionCount.x, 1, 1, baseSectionId);
        translucencyCommandBuffer.data[(uint(regionCount) - gl_WorkGroupID.x) - 1] = uvec4(totalSectionCount.y, 1, 1, baseSectionId);
        temporalCommandBuffer.data[gl_WorkGroupID.x] = uvec4(totalSectionCount.z, 1, 1, baseSectionId);
    }
}